### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kamontia** [kamontia/qs#12]
例外処理を検討、実装する

### 例外処理の検討

**Comment by chaspy** [comment]
I think this command need to pre-check if it can be rebased.
i.e: user specify -n 4, but commit log has only 4 commit.

we need the following condition.

`if <-n number> > commit log number && NOT include initial commit`

**Comment by kamontia** [comment]
I will rely on embedded error handling in Golang.
Beforehand, one stores the latest reflog hash. If an error occurs(catch by embedded error handling), executing the command git reset --hard the latest reflog hash.

**Comment by kamontia** [comment]
We discussed error handling. 
- ref : #28 
- validation argument

**Comment by kamontia** [comment]
We discussed error handling. 
- ref : #28 
- validation argument
