### ISSUE TITLE
Aggregate commit messages into one

### ISSUE THREAD

**Issue by kamontia** [kamontia/qs#17]
squash だと対象となるコミット数のログが squash先のログに入る。
```
commit 471bee06204e69b1873fa01d0d657df949577746 (HEAD -> master)
Author: git fixup <git-fixup@example.com>
Date:   Sat Aug 18 18:18:06 2018 +0900

    Add file-5

    squash! Add file-5

    squash! Add file-5

    squash! Add file-5

    squash! Add file-5

    squash! Add file-5
```

これを
オプション指定(仮に-m)で次の動作を満たす実装を行う
- [x] -m が指定されていない場合は、squash先のコミットログを採用する
- [ ] -m 数値 の場合は、squash対象となるコメントメッセージ[]のインデックスを採用する
- [x] -m 文字列の場合は、集約後のコミットログを指定した文字列に変更する

**Comment by chaspy** [comment]
@kamontia 
sorry! I don't implement -m <number>!

**Comment by chaspy** [comment]
done!
