### ISSUE TITLE
Download dependent packages from the current branch

### ISSUE THREAD

**Issue by chaspy** [kamontia/qs#19]
ref: https://github.com/kamontia/qs/pull/18#issuecomment-414053989

if we added new package in feature branch, CI failed.

**Comment by chaspy** [comment]
I'll update this line.
https://github.com/kamontia/qs/blob/f92c409336d3780bc14e7861973592b1b3981285/.circleci/config.yml#L10

**Comment by chaspy** [comment]
let's use [dep](https://github.com/golang/dep)!

**Comment by chaspy** [comment]
@kamontia 
Be careful what you develop under $GOPATH/src/...

**Comment by chaspy** [comment]
@kamontia 
if you check that `dep` works on your environment, please close this issue.

**Comment by kamontia** [comment]
Thank you for your efforts.
