### ISSUE TITLE
Refactor main.go

### ISSUE THREAD

**Issue by chaspy** [kamontia/qs#21]
main.go is very fat.

**Comment by chaspy** [comment]
@kamontia 
let's think the purpose and ToDo!

**Comment by kamontia** [comment]
- [ ] Functionalize common processing unit
- [ ] Group related variables
- [ ] Update unintelligible d variable names
- [ ] Clear conditional branch more

**Comment by chaspy** [comment]
- [ ] Scope variables appropriately

**Comment by chaspy** [comment]
hi, @kamontia 
"refactoring" is too large issue.
could you close this issue and open new issue according to #76

**Comment by kamontia** [comment]
@chaspy I think so, too.
