### ISSUE TITLE
Review by @matsu0228

### ISSUE THREAD

**Issue by chaspy** [kamontia/qs#76]
if we ready to review!

**Comment by chaspy** [comment]
hi! @matsu0228
Sorry for sudden requests.
I and @kamontia first made a CLI tool with golang.
But we don't know the "Go Language" writing.
I will be happy if you give advice when you have time.

**Comment by matsu0228** [comment]
英語で書くのは辛いので日本語でｗ

*cli package: 
```
https://github.com/urfave/cli
を使ったことないから、なんともだけど、
こっちの方が使われること多い印象！
https://github.com/spf13/cobra
```

* グローバル変数使いすぎでメンテが大変そうな印象。
  *  入出力が定義されておらずに、グローバル変数を直接書き換えているので、unitテストも大変？
  * たとえばこんなふうにすると、unitテストしやすいのでは
```
func getCommitHash() ([]string, int, error) {
	out, err := exec.Command("git", "log", "--oneline", "--format=%h").Output()
	if err != nil {
		return []string{}, 0, err
	}

	for _, v := range regexp.MustCompile("\r\n|\n|\r").Split(string(out), -1) {
		commitHashList = append(commitHashList, v)
	}

	headMax = len(commitHashList) - 2
	return commitHashList, headMax, nil
}
```

* よくみると、ほんとに引き回す必要があるデータと、取得だけできればいいデータもありそうなので、こうするとよい？
```
type gitCommitInfo struct {
	rangeArray             []string
	commitHashList         []string
	commitMsgList          []string
	commitNewMsgList       []string
	commitSpecifiedMsgList []string
}

func (g gitCommitInfo) getHeadMax() int {
	return len(g.commitHashList) - 2
}
```

* `exec.Command`のテストについては、たとえば[これ](https://qiita.com/yuya_takeyama/items/11cb60466a3f11dd1e3b)とか参考にすると、unitテストもかけそう？（自分は経験ないのでなんともだけど）

**Comment by kamontia** [comment]
@matsu0228 Thank you for your advice.
ありがとうございます。参考にさせて頂いて少しだけ修正しました。それぞれの関数でIN/OUTは意識した作りにするべきですね。まだ積み残しがあるので、v1.1.0で対応します！


Go言語のことはあまり気にかけてなかったんですが、最初のmkmkで「Go言語はいいよ」っていうの聞いてやってみたら本当によかったです。ありがとうございます。

**Comment by matsu0228** [comment]
This project encourage me :)
So, if you have some problems at golang, please ask me.

**Comment by kamontia** [comment]
@chaspy , @matsu0228  Thank you!
